name: Trigger image build

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  trigger_main_build:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build TinyTicker RPi image
          repo: loiccoyle/private.actionsrunner
          token: ${{ secrets.PRIVATE_RUNNER_ACCESS_TOKEN }}
          ref: refs/heads/main # https://github.com/benc-uk/workflow-dispatch/issues/11
