name: CI
on:
  push:

jobs:
  ci:
    name: Run tests
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10"]
        poetry-version: [1.6.1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Configure poetry
        run: poetry config virtualenvs.in-project true
      - name: Set up cache
        uses: actions/cache@v3
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Ensure cache is healthy
        if: steps.cache.outputs.cache-hit == 'true'
        run: poetry run pip --version >/dev/null 2>&1 || rm -rf .venv
      - name: Install dependencies
        run: |
          poetry run pip install --upgrade pip
          poetry install --all-extras
      - name: Run pytest
        run: poetry run pytest -q tests -v
        env:
          CRYPTOCOMPARE_API_KEY: ${{secrets.CRYPTOCOMPARE_API_KEY}}

  publish:
    name: Publish to pypi
    needs: ci
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish Package
        uses: celsiusnarhwal/poetry-publish@v2
        with:
          python-version: "3.10"
          poetry-version: 1.6.1
          token: ${{ secrets.PYPI_API_TOKEN }}
          build: true

  trigger_image_build:
    name: Trigger tinyticker disk image build
    needs: publish
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Build TinyTicker RPi image
          repo: loiccoyle/private.actionsrunner
          token: ${{ secrets.PRIVATE_RUNNER_ACCESS_TOKEN }}
          ref: refs/heads/main # https://github.com/benc-uk/workflow-dispatch/issues/11
